# -*- coding: utf-8 -*-
"""Cópia de CEPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ss9y5qsphAIAok6YJqB2iugz2nhZ5-Kt
"""

import requests

def buscacep():
  print('------------------CEPython-----------------')
  cep = input("Qual o CEP para consulta?")
  while len(cep) != 8:
    print('Quantidade de digitos invalida!')
    cep = input("Digite o Cep p/ consulta?")

  caixinha = requests.get('https://viacep.com.br/ws/{}/json/'.format(cep))
  endereco = caixinha.json()

  if 'erro' not in endereco:
    print('====>CEP ENCONTRADO<===')
    print('CEP:{}'.format(endereco['cep']))
    print('Cidade:{}'.format(endereco['localidade']))
    print('Estado:{}'.format(endereco['uf']))
    #print(endereco['cep'])
  else:
    print('{} é um CEP invalido ou nao foi encontrado'.format(cep))

    executar = True
    while executar :
      opcao = input('Escolha: \n[1]Buscar um CEP\n[2]Sair?\n')
      if opcao == '1':
        buscacep()
      else:
        executar = False
    buscacep()
