# -*- coding: utf-8 -*-
"""cobra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqrbPIhVUBBJMEszlyNp1Pk7tV2ubQLq
"""

import turtle
import random
import time

tela = turtle.Screen()
tela.title("Jogo da Cobrinha")

pontos = 0
tempo = 60
cobra_tamanho = 0

tela.bgcolor('black')
tela.setup(width=600, height=600)
tela.tracer(0)

#aqui nasce uma serpente esfomeada!
cobra = turtle.Turtle()
cobra.speed(0)
cobra.shape('square')
cobra.color('white')
cobra.penup()
cobra.direction = 'stop'
cobra.tamanho = 0

comida = turtle.Turtle()
comida.speed(0)
comida.shape('circle')
comida.color('red')
comida.penup()
comida.goto(100,100)

def vai_para_direita():
  cobra.direcion = "direita"

def vai_para_esquerda():
  cobra.direction = "esquerda"

def vai_para_cima():
  cobra.direction = "cima"

def vai_para_baixo():
  cobra.direction = "baixo"

def vai_para_centro():
    cobra.goto(0,0)

tela.listen()
tela.onkeypress(vai_para_direita, "Right")
tela.onkeypress(vai_para_esquerda, "Left")
tela.onkeypress(vai_para_cima, "Up")
tela.onkeypress(vai_para_baixo, "Down")

## O jogo começa aqui

while tempo > 0:
  tela.update()
  if cobra.distance(comida) < 20:
    x = random.randint(-290,290)
    y = random.randint(-290,290) 
    comida.goto(x,y)
    cobra_tamanho = cobra_tamanho + 1
    pontos = pontos + 10
    tela.title(f"Pontos: {Pontos}")

time.sleep(0.1)
tempo = tempo - 0.1
tela.title(f'Tempo{tempo} - Pontos:{pontos}')

if cobra.direction == 'direita':
  x = cobra.xcor()
  cobra.setx(x +20)
if cobra.direction == 'esquerda':
  x = cobra.xcor()
  cobra.setx(x -20)
if cobra.direction == 'cima':
  y = cobra.ycor()
  cobra.sety(y +20)
if cobra.direction == 'baixo':
  y = cobra.ycor()
  cobra.sety(y -20)
## O jogo termina aqui

tela.title("Jogo finalizado! Pontuação Final:{}".format(pontos))
cobra.goto(0.0)
cobra.direction = "parado"
tela.mainloop()